language: node_js
node_js:
  - "8.9.4"
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
# coveralls
jobs:
  include: Produce Coverage
  node_js: node_js
  script: npm run test:unit && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage