language: node_js
node_js:
  - "8.9.4"
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install
# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build
